
INSERT INTO PLANTED (ID, PLANTING_AREA, EXPECTED_PRODUCT, CROP_NAME, FARM_NAME) VALUES (1, 3.5, 69.3, 'corn', 'testfarm');
INSERT INTO PLANTED (ID, PLANTING_AREA, EXPECTED_PRODUCT, CROP_NAME, FARM_NAME) VALUES (2, 4.0, 68.5, 'apple', 'testfarm');
INSERT INTO PLANTED (ID, PLANTING_AREA, EXPECTED_PRODUCT, CROP_NAME, FARM_NAME) VALUES (3, 2.2, 45.8, 'berry', 'testfarm');
INSERT INTO PLANTED (ID, PLANTING_AREA, EXPECTED_PRODUCT, CROP_NAME, FARM_NAME) VALUES (4, 5.6, 65.8, 'guava', 'testfarm');
INSERT INTO PLANTED (ID, PLANTING_AREA, EXPECTED_PRODUCT, CROP_NAME, FARM_NAME) VALUES (5, 7.3, 75.2, 'chilli', 'testfarm');

INSERT INTO HARVESTED (ID, HARVESTED_PRODUCT, CROP_NAME, FARM_NAME) VALUES (1, 19.3, 'corn', 'testfarm');
INSERT INTO HARVESTED (ID, HARVESTED_PRODUCT, CROP_NAME, FARM_NAME) VALUES (2, 28.5, 'apple', 'testfarm');
INSERT INTO HARVESTED (ID, HARVESTED_PRODUCT, CROP_NAME, FARM_NAME) VALUES (3, 35.8, 'berry', 'testfarm');
INSERT INTO HARVESTED (ID, HARVESTED_PRODUCT, CROP_NAME, FARM_NAME) VALUES (4, 25.8, 'guava', 'testfarm');
INSERT INTO HARVESTED (ID, HARVESTED_PRODUCT, CROP_NAME, FARM_NAME) VALUES (5, 28.2, 'chilli', 'testfarm');

